# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    paths: 
      - 'Implementation/**'
      - '.github/workflows/**'
    branches: [ main ]
  pull_request:
    paths: 
      - 'Implementation/**'
      - '.github/workflows/**'
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        path: ~Implementation/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/.gradle') }}
        restore-keys: ${{ runner.os }}-gradle
    - name: Grant execute permission for gradlew
      run: chmod +x Implementation/gradlew
    - name: Build lwjgl3 JAR 
      run: cd Implementation && ./gradlew lwjgl3:dist
    - uses: actions/upload-artifact@v2
      with:
        name: Package
        path: Implementation/lwjgl3/build/libs
